### ISSUE TITLE
Let chickens that don't produce other chickens be placed in breeder

### ISSUE THREAD

**Issue by Stv13579** [TarantelTM/chicken_roost#1]
Title. Chickens that don't produce different types of chickens should still be able to be put in the breeder, especially chickens that are used for upgrading roosts.

**Comment by TarantelTM** [comment]
Hi
maybe i add some of the chickens too to the breeder.
atm thinking about a better breedtable for later versions.

**Comment by TarantelTM** [comment]
Already done in 1.19.2 4.0
Also planned for 1.16.5 and 1.18.2 still work in progress.
