### ISSUE TITLE
Too many of them

### ISSUE THREAD

**Issue by ghost** [TarantelTM/chicken_roost#10]
![QQ图片20230119171300](https://user-images.githubusercontent.com/83486178/213402120-2265f25d-da79-47c2-ad64-477120c74167.png)
roost_ultimate-1.19.2-0.2.7

**Comment by ghost** [comment]
![QQ图片20230119171627](https://user-images.githubusercontent.com/83486178/213402854-93df9ad8-a552-4066-b574-9b188011e6a9.png)

**Comment by ghost** [comment]
The game lag is very serious

**Comment by NJM1564** [comment]
That's not to mannn... glances at map. Oh!

**Comment by TarantelTM** [comment]
Will try my best to adjust the spawnrates.
Still not familar with the new Spawnsystem of Minecraft/Forge.

**Comment by Yourname942** [comment]
Is there a config to fine tune to our needs? If not, please add one! Thank you

**Comment by TarantelTM** [comment]
Should be fixed in the latest Update.
