### ISSUE TITLE
Automated piping into Breeder fills output slots as well

### ISSUE THREAD

**Issue by TheAtlasCo** [TarantelTM/chicken_roost#11]
When trying to transport seeds into breeder (whether using mekanism transporters or a hopper) it will fill the output slots as well once input slots are filled.

**Comment by TarantelTM** [comment]
Hello
Which Version of MC and which Version of Roost Ultimate u use ?

**Comment by TarantelTM** [comment]
ok i see it in 1.0.0 of 1.19.2 and 1.19.3
will fix it in the next update.

**Comment by TarantelTM** [comment]
Fixed in 1.0.1 in 1.19.2, 1.19.3 and 1.19.4
