### ISSUE TITLE
Netherrack chicken and few others have a broken model [1.16.5]

### ISSUE THREAD

**Issue by Xplodin** [TarantelTM/chicken_roost#12]
Im playing on custom modpack and with roost ultimate some chickens have the correct texture but have player model instead of chicken model which makes the texture bug out
![image](https://user-images.githubusercontent.com/13007677/226449946-9e684fef-d9e1-4789-8e2e-b58c3fefaafa.png)

**Comment by TarantelTM** [comment]
Oh thats rly weird xD
Will check that

**Comment by TarantelTM** [comment]
u use the newest version for 1.16.5 of Roost Ultimate ?
