### ISSUE TITLE
Version 1.19.2, Multiplayer, players can't connect

### ISSUE THREAD

**Issue by Eos109** [TarantelTM/chicken_roost#14]
Singleplayer works without issue, but after adding it (only change) to our modpack the users can't connect anymore. server start up is fine. this is the message that players trying to connect get. Is this a thing from the mod or is it a thing with the servers Java?
![Screenshot 2023-07-11 223018](https://github.com/TarantelTM/chicken_roost/assets/111760018/1245af7e-6c39-4fb3-842b-d09c65d7b853)

**Comment by TarantelTM** [comment]
Hello,

Will check that.
Btw Forge or Fabric ?
So i know which Project

**Comment by Eos109** [comment]
We are using forge

**Comment by TarantelTM** [comment]
ok will check that

**Comment by TarantelTM** [comment]
and sorry got some problems with my system xD

**Comment by Eos109** [comment]
yeah no prob

**Comment by Spodi** [comment]
welp, im getting the same error with my server. Tried to replace ftb one's chicken mod with this, casuse theirs was way too OP and not really configurable

**Comment by EliteXT** [comment]
yeah i also have the same problem but its only on version 1.0.1 after the the same message showed up i installed version 1.0.0 and tried joining my server and then BOOM! it was working to I'd recommend you installing V1.0.0

**Comment by TarantelTM** [comment]
Hello,

Will do a lot bugfixing in the next versions.
My RL Job kicking me out of modding atm ^^
But i try my best to work on my Mod from time to time.

**Comment by MidCoard** [comment]
if you can make the mod open-source I can provide pull request to simply fix it

**Comment by TarantelTM** [comment]
> if you can make the mod open-source I can provide pull request to simply fix it

Hello
Atm im full out of modding because of a long stop for RL.
If u point me in the right direction i will fix it ^^
Atm cant see from where it came.
The Exception changes in any Forge Version too xD
And i get no output from Log, Debuglog or Crashlog.
Atm hanging on multiple other fixes for all versions :(

Dont want to make it open source, because i have no time to deal with reuploads.

**Comment by MidCoard** [comment]
In net.tarantel.chickenroost.recipemanager.BasicBreedingRecipe$Serializer, the fromNetwork method does not match the toNetwork method. You have written some extra things to the packet in toNetwork method.

**Comment by MidCoard** [comment]
Seems like the extra things is not necessary. And the 1.0.0 version of this is right and works fine. So simply downgrading this file to 1.0.0 version is ok.

**Comment by TarantelTM** [comment]
> In net.tarantel.chickenroost.recipemanager.BasicBreedingRecipe$Serializer, the fromNetwork method does not match the toNetwork method. You have written some extra things to the packet in toNetwork method.

Thanks ^^
Looks like i forgot some testing code snippets inside :)
