### ISSUE TITLE
Client disconnect from server in multiplayer play.

### ISSUE THREAD

**Issue by WarMind666** [TarantelTM/chicken_roost#16]
While playing on a Fabric multiplayer server for 1.19.2, I attempted to interact with the Roost, and received the following error screen.  I made the same attempt with the Breeder, and saw the same.  Minecraft version, mod version, and fabric loader version are included below.

Minecraft Version:  1.19.2
Mod Version:  roost_ultmate-0.9.0-1.19.2 [FABRIC].jar (downloaded from Curseforge, no other versions show as available.)
Mod Loader: Fabric
Fabric Version:  0.14.21
Fabric API Version:  fabric-api-0.76.0+1.19.2.jar

![image](https://github.com/TarantelTM/chicken_roost/assets/17150751/2b92d03f-175d-4ab8-b766-68f1b6e4d460)

**Comment by TarantelTM** [comment]
Will check that ^^

**Comment by TarantelTM** [comment]
sorry for this late answer.
fixed in the newer version 0.9.1
