### ISSUE TITLE
Multiplayer - Players crash when trying to open any type of block from Roost but not the host

### ISSUE THREAD

**Issue by FlameinfirenBr** [TarantelTM/chicken_roost#18]
![image](https://github.com/TarantelTM/chicken_roost/assets/42920230/31991826-068f-4027-af93-0e4281dcdf69)
Here's the error from one of the players

**Comment by TarantelTM** [comment]
Hello
Which Version of MC u use and its Forge or Fabric ?

**Comment by TarantelTM** [comment]
if u play on 1.19.2 it should be fixed in Version 0.9.1
if u play on 1.20.X please reopen.
