### ISSUE TITLE
Stone family of chickens do not produce stone chickens in breeders 1.18.2

### ISSUE THREAD

**Issue by Stv13579** [TarantelTM/chicken_roost#2]
According to the document showing all chicken breed outcomes, Cobble, Andesite, Diorite, and Granite chickens should produce Stone chickens in a breeder, however they do not.

**Comment by TarantelTM** [comment]
oh i will check that

**Comment by TarantelTM** [comment]
Will be fixed in the next update for 1.16.5/1.18.2 and 1.19
