### ISSUE TITLE
Progression hampered by requirements

### ISSUE THREAD

**Issue by AngleWyrm10** [TarantelTM/chicken_roost#6]
Finding a plain chicken is no longer common; the world is filled with variety. This is a good thing, I like seeing all kinds of different chickens. But it also means requiring a plain chicken as an ingredient is an exercise in frustration.

And breeding the chickens is nearly impossible. Even a tier-1 Acacia chicken refuses to go into the breeder. I've had to remove the mod from my mod pack because it doesn't let the player raise chickens that inhabit the land, which was it's primary purpose.

**Comment by TarantelTM** [comment]
Hello

Yeah only specific Chickens are breedable atm.
Acacia, Oak or Birch Chickens spawn only in specific regions and cant be breeded atm.
In the next bigger updates i add a way to breed them too.
For now the breeder exist only to create complete new Chickens.

For the variety of Chickens i added in the new update 0.2.9 the option to set Spawnrates, Spawnweight and min and max group sizes on your own.
U have also the option to disable some chicken spawnings or to disable all chickens to spawn.

In future updates i change the breedsystem to the old known system from the original roost of 1.12.2 and i will add some other breeder options too.

**Comment by TarantelTM** [comment]
Already added the option to breed any chicken via Soul Breeding in 1.19.2 4.0
For 1.16.5 and 1.18.2 wait for Patch 4.0 for them too.
