### ISSUE TITLE
Loading error 1.19

### ISSUE THREAD

**Issue by Zukamia** [TarantelTM/chicken_roost#7]
[crash-2022-09-22_17.02.39-fml.txt](https://github.com/TarantelTM/chicken_roost/files/9629102/crash-2022-09-22_17.02.39-fml.txt)
![error-1](https://user-images.githubusercontent.com/95436039/191840695-aaed1af5-58a9-4707-959b-0182d94661ee.png)
![error-2](https://user-images.githubusercontent.com/95436039/191840700-fa3ce98e-52a2-409d-b989-d3c2667e7fe8.png)

**Comment by TarantelTM** [comment]
Yeah u running 1.19.2
But the Mod Version is only for 1.19 atm
I will update it for 1.19.1 and 1.19.2 later.
Atm i need to update the code because 1.19.1 and 1.19.2 changed again alot of code.
