### ISSUE TITLE
Breaking roosts drops an Empty Roost

### ISSUE THREAD

**Issue by jgaines** [TarantelTM/chicken_roost#8]
Running 1.16.5 0.3.3 (modpack Crazy Craft Updated), I tried normal axe and a silk touch axe (I even busted one using the chicken stick just on the off chance that worked like a wrench).  Every time I got back an Empty Roost, tried with both tier 1 and tier 2 roosts.  The only way I was able to move a roost after placement was using a cardboard box from Mekanism.  (I'm guessing Carry On or something like that might work too, just don't have that in my current mod pack.)

**Comment by TarantelTM** [comment]
Will be fixed in the next bigger Patch 4.0/4.1
