### ISSUE TITLE
Glow Berries Chicken not producing anything

### ISSUE THREAD

**Issue by jgaines** [TarantelTM/chicken_roost#9]
Crazy Craft Updated modpack, upgraded roost ultimate to 1.16.5 0.3.0, have gone through 2 stacks of seeds and not seen any output from the Glow Berries Chicken.  It's in a tier 2 roost and I haven't leveled up the chicken at all.  I tossed in a Sweet Berries chicken just to make sure roost works and it produced sweet berries right away.

**Comment by TarantelTM** [comment]
Will check that and the other issue too.

**Comment by TarantelTM** [comment]
Will be fixed in the next bigger Patch 4.0/4.1
